"""create hair tables

Revision ID: 1ed42c441b96
Revises: ee38a35f5526
Create Date: 2026-10-02 03:24:26.689444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ed42c441b96'
down_revision: Union[str, Sequence[str], None] = 'ee38a35f5526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hair_style_catalog',
    sa.Column('style_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('length', sa.String(length=30), nullable=False),
    sa.Column('texture', sa.String(length=30), nullable=False),
    sa.Column('face_fit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('guide', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('style_id', name=op.f('pk_hair_style_catalog'))
    )
    op.create_table('user_hair_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('texture_pref', sa.String(length=30), nullable=True),
    sa.Column('length_pref', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_hair_preferences'))
    )
    op.create_table('face_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Uuid(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('face_shape', sa.String(length=20), nullable=False),
    sa.Column('top2', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ratios', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_face_analyses_image_id_images'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_analyses'))
    )
    op.create_index(op.f('ix_face_analyses_guest_id'), 'face_analyses', ['guest_id'], unique=False)
    op.create_index(op.f('ix_face_analyses_user_id'), 'face_analyses', ['user_id'], unique=False)
    op.create_table('hair_rec_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Uuid(), nullable=True),
    sa.Column('face_analysis_id', sa.Integer(), nullable=False),
    sa.Column('preferred_length', sa.String(length=30), nullable=True),
    sa.Column('preferred_texture', sa.String(length=30), nullable=True),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_n', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['face_analysis_id'], ['face_analyses.id'], name=op.f('fk_hair_rec_runs_face_analysis_id_face_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hair_rec_runs'))
    )
    op.create_index(op.f('ix_hair_rec_runs_face_analysis_id'), 'hair_rec_runs', ['face_analysis_id'], unique=False)
    op.create_index(op.f('ix_hair_rec_runs_guest_id'), 'hair_rec_runs', ['guest_id'], unique=False)
    op.create_index(op.f('ix_hair_rec_runs_user_id'), 'hair_rec_runs', ['user_id'], unique=False)
    op.create_table('hair_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('style_id', sa.String(length=50), nullable=False),
    sa.Column('face_fit', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('texture_fit', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('length_fit', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['hair_rec_runs.id'], name=op.f('fk_hair_recommendations_run_id_hair_rec_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_id'], ['hair_style_catalog.style_id'], name=op.f('fk_hair_recommendations_style_id_hair_style_catalog')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hair_recommendations')),
    sa.UniqueConstraint('run_id', 'rank', name=op.f('uq_hair_recommendations_run_id'))
    )
    op.create_index(op.f('ix_hair_recommendations_run_id'), 'hair_recommendations', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hair_recommendations_run_id'), table_name='hair_recommendations')
    op.drop_table('hair_recommendations')
    op.drop_index(op.f('ix_hair_rec_runs_user_id'), table_name='hair_rec_runs')
    op.drop_index(op.f('ix_hair_rec_runs_guest_id'), table_name='hair_rec_runs')
    op.drop_index(op.f('ix_hair_rec_runs_face_analysis_id'), table_name='hair_rec_runs')
    op.drop_table('hair_rec_runs')
    op.drop_index(op.f('ix_face_analyses_user_id'), table_name='face_analyses')
    op.drop_index(op.f('ix_face_analyses_guest_id'), table_name='face_analyses')
    op.drop_table('face_analyses')
    op.drop_table('user_hair_preferences')
    op.drop_table('hair_style_catalog')
    # ### end Alembic commands ###
