"""create cosmetic tables

Revision ID: ee38a35f5526
Revises: 4f12eb785a30
Create Date: 2026-09-29 11:30:42.350573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee38a35f5526'
down_revision: Union[str, Sequence[str], None] = '4f12eb785a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('brand_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('brand_id', name=op.f('pk_brands')),
    sa.UniqueConstraint('brand_name', name=op.f('uq_brands_brand_name'))
    )
    op.create_table('ingredients',
    sa.Column('ingredient_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ingredient_name', sa.String(length=255), nullable=False),
    sa.Column('name_inci', sa.String(length=255), nullable=True),
    sa.Column('normalized_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ingredient_id', name=op.f('pk_ingredients')),
    sa.UniqueConstraint('ingredient_name', name=op.f('uq_ingredients_ingredient_name'))
    )
    op.create_table('products',
    sa.Column('product_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('ingredients_raw', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], name=op.f('fk_products_brand_id_brands')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_products'))
    )
    op.create_table('product_ingredients',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], name=op.f('fk_product_ingredients_ingredient_id_ingredients')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('fk_product_ingredients_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'ingredient_id', name=op.f('pk_product_ingredients'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_ingredients')
    op.drop_table('products')
    op.drop_table('ingredients')
    op.drop_table('brands')
    # ### end Alembic commands ###
