"""allow null texture_fit length_fit

Revision ID: 400e4e798f5c
Revises: 1ed42c441b96
Create Date: 2026-10-02 04:00:05.757097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '400e4e798f5c'
down_revision: Union[str, Sequence[str], None] = '1ed42c441b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hair_recommendations', 'texture_fit',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True)
    op.alter_column('hair_recommendations', 'length_fit',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hair_recommendations', 'length_fit',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False)
    op.alter_column('hair_recommendations', 'texture_fit',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False)
    # ### end Alembic commands ###
